[general]
UPDATE_USER_PORTFOLIO = false
READ_RSS = false        
SCRAP_ARTICLES_CONTENT = false
UPDATE_STOCKS_DB = true
UPDATE_NEWS_DB = true

[models]
llm_model_api = 'dbrx'
embdelling_model_name = "thenlper/gte-large"

[data]
location = "data"
    [data.user_portfolio]
    filename = "user_portfolio.csv"
    location = "user_portfolio"

    [data.vector_db]
    location = "vector_db"
        [data.vector_db.news]
        location = "news_vector_db"
        news_collection_name = "news"

        [data.vector_db.stocks]
        location = "stocks_vector_db"
        stocks_collection_name = "stocks"

    [data.news]
        [data.news.rss_feed]
        location = "rss_feed"
        filename = "rss_feed_df.csv"

        [data.news.rss_feed_with_content]
        location = "rss_feed_with_content"
        filename = "rss_feed_with_content_df.csv"
    
    [data.dashboard]
    location = "dashboard"
    filename = "user_dashboard.csv"

    [data.stocks]
    location = "stocks"
    filename = "sp500_enriched.csv"

[rag]
    [rag.news]
    news_date_threshold = 10
    top_articles_k = 5

    [rag.stock]
