rss_urls:
  - "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664"
  - "https://ec.europa.eu/eurostat/en/search?p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=2&p_p_state=maximized&p_p_mode=view&p_p_resource_id=atom&_estatsearchportlet_WAR_estatsearchportlet_collection=dataset"
  - "https://feeds.content.dowjones.io/public/rss/mw_topstories"
  - "https://feeds.content.dowjones.io/public/rss/mw_realtimeheadlines"
  - "http://feeds.marketwatch.com/marketwatch/bulletins"
  - "https://feeds.content.dowjones.io/public/rss/mw_marketpulse"
  - "https://www.oecd.org/economy/index.xml"
  - "https://www.economist.com/letters/rss.xml"
  - "http://www.oecd.org/finance/index.xml"
  - "http://www.oecd.org/investment/index.xml"
  - "http://www.oecd.org/industry/index.xml"
  - "http://www.oecd.org/corporate/index.xml"
  - "https://economic-research.bnpparibas.com/RSS/en-US/Eco-Flash"
  - "https://economic-research.bnpparibas.com/RSS/en-US/Eco-Perspectives"
  - "https://economic-research.bnpparibas.com/RSS/en-US/Eco-Week"
  - "https://economic-research.bnpparibas.com/RSS/en-US/Eco-Conjoncture"
  - "https://economic-research.bnpparibas.com/RSS/en-US/Eco-Emerging"
  - "https://economic-research.bnpparibas.com/RSS/en-US/Eco-Brief"
  - "https://feeds.a.dj.com/rss/RSSMarketsMain.xml"
  - "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml"
  - "https://ec.europa.eu/eurostat/en/search?p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=2&p_p_state=maximized&p_p_mode=view&p_p_resource_id=atom&_estatsearchportlet_WAR_estatsearchportlet_theme=PER_ECOFIN&_estatsearchportlet_WAR_estatsearchportlet_collection=CAT_EURNEW"
